# Generated by Django 3.2.10 on 2024-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collegedb',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_No', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='coursedb',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(blank=True, max_length=100, null=True)),
                ('Duration', models.CharField(blank=True, max_length=100, null=True)),
                ('Fees', models.IntegerField(blank=True, null=True)),
                ('HODname', models.CharField(blank=True, max_length=100, null=True)),
                ('HOD_mo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sdb',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('f_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contactno', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
